name: "patients-management"
services:

  db:
    image: postgres:latest
    networks:
      - internal
    container_name: patient-service-db
    restart: always

    volumes:
      - type: bind
        source: C:/Users/user/patients-db
        target: /var/lib/postgresql/data

    environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: db

    ports:
      - "5000:5432"

    expose:
      - "5000"

  patient-service:
    build:
      context: ../patient-service
      dockerfile: Dockerfile
    image: patient-service:latest
    container_name: patient-service
    ports:
      - "4000:4000"
    expose:
      - "4000"
    env_file:
      - env.dev

    networks:
      - internal

  billing-service:
    build:
      context: ../billing-service
      dockerfile: Dockerfile
    image: billing-service:latest
    container_name: billing-service
    ports:
      - "4001:9001"
    expose:
      - "4001"
    networks:
      - internal

  kafka:
      image: 'bitnami/kafka:latest'
      container_name: kafka
      networks:
        - internal
      env_file:
        - env.dev

      ports:
        - "9092:9092"
        - "9094:9094"
      expose:
        - "9092"
        - "9094"

networks:

  internal:
    name: internal

